source_file: "A7M3hSLI000100NR2D.JPG"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "72745a09"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "7151d0bdc99e1179f4d458096b9733b6"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "848e6ee0189507fc75effa5f83b0441e14a011ab"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "SONY ILCE-7M3 28ff00008809 27"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "17128474"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931558"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/A7M3hSLI000100NR2D.JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "4d41968987274d7e"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "bf8181c3e78391db.9692986861c8cacc"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "WY4Bc6H/CyRPW1dtUBnEpg7f1k4m5cvHGjLb0fc/Fl0gWG3Hw3wZA70NGTjfwvHogn3I+HRGGRG7Es6Xk27fTm0YEn47/SV2"
  want_quality: 20
}
exif: {
  want_camera_model: "SONY ILCE-7M3"
  want_camera_serial: "28ff00008809"
  want_photo_id: "27"
}
xmp: {}
img_phash: {
  want_azr_hash: "4d41968987274d7e"
  want_nr90_hash: "bf8181c3e78391db.9692986861c8cacc"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "72745a09"
  verified_crc32: "72745a09"
  md5: "7151d0bdc99e1179f4d458096b9733b6"
  verified_md5: "7151d0bdc99e1179f4d458096b9733b6"
  sha1: "848e6ee0189507fc75effa5f83b0441e14a011ab"
  verified_sha1: "848e6ee0189507fc75effa5f83b0441e14a011ab"
}
