source_file: "Adobe Photoshop Lightroom.XMP"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "767d6278"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "5b437bb3efd84987e804187f658f2069"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "1bf7e8a34aaba989df9d1674408b1e63f248dfcb"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "8412"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931559"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/Adobe Photoshop Lightroom.XMP"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".XMP"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_quality: 10
}
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "no image data"
}
video_phash: {
  comment: "no video data"
}
checksum: {
  crc32: "767d6278"
  verified_crc32: "767d6278"
  md5: "5b437bb3efd84987e804187f658f2069"
  verified_md5: "5b437bb3efd84987e804187f658f2069"
  sha1: "1bf7e8a34aaba989df9d1674408b1e63f248dfcb"
  verified_sha1: "1bf7e8a34aaba989df9d1674408b1e63f248dfcb"
}
