source_file: "BigBuckBunny.gif"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "ebc05db5"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "3c931dc0ce4bb84a4bb6666da811cb7d"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "799e9651e92ac4e5468584a8819f8e398392ce4a"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "2914289"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1739785059"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/BigBuckBunny.gif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".gif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/gif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "1a7344a9395c576a"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "efe0e0f8c8ccc4c0.eb793454e6c7e6fc"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "TXUTo142ZlPEH5ywjOVfIVY9nmH2IdHY7VytpBMlSHnFDCjKVnIw7uQ4zB8EawbHqhVoXXWcO+Hg5rlyFKrNaLYJH2Y/DbPa"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "VideoPHashRicop"
  want_hash: "f86e2e4a34601020.aa55aa554555aa55"
  want_quality: 20
}
exif: {
  comment: "TODO: gif files have no EXIF data"
  skip: true
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "1a7344a9395c576a"
  want_nr90_hash: "efe0e0f8c8ccc4c0.eb793454e6c7e6fc"
}
video_phash: {
  want_ricop_hash: "f86e2e4a34601020.aa5555aa15aa5555"
}
checksum: {
  crc32: "ebc05db5"
  verified_crc32: "ebc05db5"
  md5: "3c931dc0ce4bb84a4bb6666da811cb7d"
  verified_md5: "3c931dc0ce4bb84a4bb6666da811cb7d"
  sha1: "799e9651e92ac4e5468584a8819f8e398392ce4a"
  verified_sha1: "799e9651e92ac4e5468584a8819f8e398392ce4a"
}
