source_file: "BigBuckBunny.ts"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "4b3a8d60"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "f9abd7191576a3f8f49221c3bfa5eb71"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "8e10a9f86654d124e9846bf21ff1c340e699a517"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1958584"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1739785073"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/BigBuckBunny.ts"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".ts"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "video/mp2t"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "VideoPHashRicop"
  want_hash: "52c4fd5de1755969.aa55a955a255aa55"
  want_quality: 20
}
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "No image data"
}
video_phash: {
  want_ricop_hash: "52c4fd5de1755969.5aaad654a92a5595"
}
checksum: {
  crc32: "4b3a8d60"
  verified_crc32: "4b3a8d60"
  md5: "f9abd7191576a3f8f49221c3bfa5eb71"
  verified_md5: "f9abd7191576a3f8f49221c3bfa5eb71"
  sha1: "8e10a9f86654d124e9846bf21ff1c340e699a517"
  verified_sha1: "8e10a9f86654d124e9846bf21ff1c340e699a517"
}
