source_file: "computerchess5.flv"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "554613a0"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "3cd4aac28c8517064827047bccb9a290"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "89b2aee9bdcb3e96ad2616fbb2a9149ed48fdb41"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "4871669"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1739785094"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/computerchess5.flv"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".flv"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "video/x-flv"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "VideoPHashRicop"
  want_hash: "3672b3d29e8b4f80.abdd0df7009de300"
  want_quality: 20
}
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "No image data"
}
video_phash: {
  want_ricop_hash: "c7c01795a798700c.b3ff00de0a5e5a40"
}
checksum: {
  crc32: "554613a0"
  verified_crc32: "554613a0"
  md5: "3cd4aac28c8517064827047bccb9a290"
  verified_md5: "3cd4aac28c8517064827047bccb9a290"
  sha1: "89b2aee9bdcb3e96ad2616fbb2a9149ed48fdb41"
  verified_sha1: "89b2aee9bdcb3e96ad2616fbb2a9149ed48fdb41"
}
