source_file: "D300hSLI0100.JPG"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "29bc04d8"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "4c6bd619c112e5a60f693287ef52fb27"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "dfc011ca25ef6114f9d48bd153cf4b652faf59ec"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "NIKON D300 3005346 1803 FINE"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "5823733"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931646"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/D300hSLI0100.JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "6c49968b07a74d5c"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "9f8581c3e78391fb.8a92984871d8dacc"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "Mf4A+KPflJMjW0dNWAnErnlN2g8nFc3AdTht0fY/FsXmpW3bw3FSo/guHhzbWwvH/k0AvH+aS24NMt7Bw4bf35/nBl1o/HNb"
  want_quality: 20
}
exif: {
  want_camera_model: "NIKON D300"
  want_camera_serial: "3005346"
  want_photo_id: "1803 FINE"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "6c49968b07a74d5c"
  want_nr90_hash: "9f8581c3e78391fb.8a92984871d8dacc"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "29bc04d8"
  verified_crc32: "29bc04d8"
  md5: "4c6bd619c112e5a60f693287ef52fb27"
  verified_md5: "4c6bd619c112e5a60f693287ef52fb27"
  sha1: "dfc011ca25ef6114f9d48bd153cf4b652faf59ec"
  verified_sha1: "dfc011ca25ef6114f9d48bd153cf4b652faf59ec"
}
