source_file: "D300hSLI0100.NEF"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "6cb80435"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "4af3f6b1b23b903ef814e956ce16f66c"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "5d2966f079eba2c9184cbbc6145cf605e27308e9"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "NIKON D300 3005346 1803 RAW"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "16918350"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931672"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/D300hSLI0100.NEF"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".NEF"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/tiff"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "4cc9b6cb63a34d14"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "87a1c7efd1f900.909a9048f1d8c82c"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "tooA9FWeNsm2tuGKPAnMuHe2JKYHE8/BcDe2tpm/BSEkbmm2JPB4UcmvFq22tqJw3D0w/Gm2tpZPKb9D5pO2tqPxE04o4c22"
  want_quality: 20
}
exif: {
  want_camera_model: "NIKON D300"
  want_camera_serial: "3005346"
  want_photo_id: "1803 RAW"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "4cc9b6cb63a34d14"
  want_nr90_hash: "87a1c7efd1f900.909a9048f1d8c82c"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "6cb80435"
  verified_crc32: "6cb80435"
  md5: "4af3f6b1b23b903ef814e956ce16f66c"
  verified_md5: "4af3f6b1b23b903ef814e956ce16f66c"
  sha1: "5d2966f079eba2c9184cbbc6145cf605e27308e9"
  verified_sha1: "5d2966f079eba2c9184cbbc6145cf605e27308e9"
}
