source_file: "heic.digital iPhone 12 Pro 1.heic"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "7850bd11"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "945c312ea398c4ab12299dda6d2b06f2"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "a9e71ed5c57ab89ff01987105016cd5b3b9bbbfb"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1721433"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932696"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/heic.digital iPhone 12 Pro 1.heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/heif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "255fa7ad5a6205a4"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "f19307e7e6c680e5.38d8a3e3a3a1a2f2"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "B5s/FD6QXQ/GLwrlMmlWMDemNq4lXcyuF6i28iX7g6WA7wumDMLKDx0AfOmAn4+H44D5GbGD8qoWPiP58RrsumhkFkIMqqWG"
  want_quality: 20
}
exif: {
  want_camera_model: "Apple iPhone 12 Pro"
  want_photo_id: "3A0C50F8-C0D5-4C4A-B746-0329F218B46E"
  want_unique_photo_id: true
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "255fa7ad5a6205a4"
  want_nr90_hash: "f19307e7e6c680e5.38d8a3e3a3a1a2f2"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "7850bd11"
  verified_crc32: "7850bd11"
  md5: "945c312ea398c4ab12299dda6d2b06f2"
  verified_md5: "945c312ea398c4ab12299dda6d2b06f2"
  sha1: "a9e71ed5c57ab89ff01987105016cd5b3b9bbbfb"
  verified_sha1: "a9e71ed5c57ab89ff01987105016cd5b3b9bbbfb"
}
