source_file: "heic.digital iPhone 12 Pro 2.heic"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "91975cf4"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "4c1aec701f97b66e756cbc44b8306efe"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "1b61164290f0153999d1ecb14ff7df9978f3fbcd"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "Apple iPhone 12 Pro  8836E8B5-A132-4292-8D7D-87CCE1CACD2A"
  want_quality: 100
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1960764"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932702"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/heic.digital iPhone 12 Pro 2.heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/heif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "788e0831fcff1f00"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "7070f0f0f0f0f03.93c3c2c2c3c39119"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "W1geETE4j9fhqPHgY9M/E5G4l0VA+BfRGdzHqn4Do8nnAnHA2c6nEaHBw6g+6PTz5EHo5HI/6OcRMkF7HizGw+Y49ixwzMTq"
  want_quality: 20
}
exif: {
  want_camera_model: "Apple iPhone 12 Pro"
  want_photo_id: "8836E8B5-A132-4292-8D7D-87CCE1CACD2A"
  want_unique_photo_id: true
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "788e0831fcff1f00"
  want_nr90_hash: "7070f0f0f0f0f03.93c3c2c2c3c39119"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "91975cf4"
  verified_crc32: "91975cf4"
  md5: "4c1aec701f97b66e756cbc44b8306efe"
  verified_md5: "4c1aec701f97b66e756cbc44b8306efe"
  sha1: "1b61164290f0153999d1ecb14ff7df9978f3fbcd"
  verified_sha1: "1b61164290f0153999d1ecb14ff7df9978f3fbcd"
}
