source_file: "heic.digital Samsung Galaxy A32 3.heic"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "9d3172cf"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "6c03a0abbd5088ffce4ac40e2b75c26e"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "ae78e4fa92b179f946abe7814a41e86bf215f897"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1220221"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932680"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/heic.digital Samsung Galaxy A32 3.heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/heif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "c58c6a9da54c24ed"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "e3c3c397cbc38100.f0eaeaaa60a8e8d4"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "nSj9XA5ALttrg6PHJnlq4xQc2OFjh4eTCwpbdIuxHpuVyxUYNR7w6j51CrTAVRq1dePFKFnCW2rZbVe0YtESaLqr8FracRUw"
  want_quality: 20
}
exif: {
  want_camera_model: "samsung SM-A326B"
  want_photo_id: "2024-01-21 18:27:07.962 +0000 UTC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "c58c6a9da54c24ed"
  want_nr90_hash: "e3c3c397cbc38100.f0eaeaaa60a8e8d4"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "9d3172cf"
  verified_crc32: "9d3172cf"
  md5: "6c03a0abbd5088ffce4ac40e2b75c26e"
  verified_md5: "6c03a0abbd5088ffce4ac40e2b75c26e"
  sha1: "ae78e4fa92b179f946abe7814a41e86bf215f897"
  verified_sha1: "ae78e4fa92b179f946abe7814a41e86bf215f897"
}
