source_file: "heic.digital iPad Air 5th gen 2.heic"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "fd8afd29"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "5ec94b19184acacf316a73cd0bc4fe2e"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "dc4b7686fa68393bc4aaec0c5ce1ad5a67625c76"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1332170"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932690"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/heic.digital iPad Air 5th gen 2.heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/heif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "4cf0f8c7c3121ed4"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "ffff7f143c3c1800.1a1a0b0a1a1a0e00"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "V8jS8upMrsOWiZ2uMmvKDl3B1W2ZPE4E6rJkHJLN0aIeYHx/vltOpNuUVjI/puevHoXB4U66lsPwke2iJl1Kq1lhy60RMUbN"
  want_quality: 20
}
exif: {
  want_camera_model: "Apple iPad Air (5th generation)"
  want_photo_id: "39247AF2-FA9F-41B3-92DF-2E53D34D582B"
  want_unique_photo_id: true
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "4cf0f8c7c3121ed4"
  want_nr90_hash: "ffff7f143c3c1800.1a1a0b0a1a1a0e00"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "fd8afd29"
  verified_crc32: "fd8afd29"
  md5: "5ec94b19184acacf316a73cd0bc4fe2e"
  verified_md5: "5ec94b19184acacf316a73cd0bc4fe2e"
  sha1: "dc4b7686fa68393bc4aaec0c5ce1ad5a67625c76"
  verified_sha1: "dc4b7686fa68393bc4aaec0c5ce1ad5a67625c76"
}
