source_file: "heic.digital Samsung Galaxy A32 1.heic"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "094589bf"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "7add2b5eb2f6127220ae02030a4bb06e"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "c68a9be64c8509cd30df77990bc74116299c6abf"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1442278"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932671"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/heic.digital Samsung Galaxy A32 1.heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/heif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "19c673334ab1664b"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "80fef2fe7e2c0000.f45f59513f374470"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "em2S02En4rda2wJTdR2mOau62pNaIv2ltNNLaF2AdiklttpL2m2Eyjlqu4A/m1tEg/knQ/JDHlKYEO9UgJJO4iSRsgr4/JOA"
  want_quality: 20
}
exif: {
  want_camera_model: "samsung SM-A326B"
  want_photo_id: "2023-12-13 13:03:39.016 +0000 UTC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "19c673334ab1664b"
  want_nr90_hash: "80fef2fe7e2c0000.f45f59513f374470"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "094589bf"
  verified_crc32: "094589bf"
  md5: "7add2b5eb2f6127220ae02030a4bb06e"
  verified_md5: "7add2b5eb2f6127220ae02030a4bb06e"
  sha1: "c68a9be64c8509cd30df77990bc74116299c6abf"
  verified_sha1: "c68a9be64c8509cd30df77990bc74116299c6abf"
}
