source_file: "heic.digital Samsung Galaxy A32 2.heic"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "09c08ade"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "b2e73c2449294c631ea11590f6dcc8ec"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "4c55482b2e5f98a0c4831de57edf1a7ab4b1662e"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1595244"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932676"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/heic.digital Samsung Galaxy A32 2.heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".heic"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/heif"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "c40aa8df24dd3987"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "45cfcfe6eee464e.5353ab2b57375755"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "6zJqTB8hyHI87Ti4pnm65PA42VpyVtmySttlw6TJ4zyvutVVA5PA5PkKXtdlHwZHwZFo6Hotn56lr8rS5JLosjJkibtqSBdt"
  want_quality: 20
}
exif: {
  want_camera_model: "samsung SM-A326B"
  want_photo_id: "2023-12-12 18:39:16.576 +0000 UTC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "c40aa8df24dd3987"
  want_nr90_hash: "45cfcfe6eee464e.5353ab2b57375755"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "09c08ade"
  verified_crc32: "09c08ade"
  md5: "b2e73c2449294c631ea11590f6dcc8ec"
  verified_md5: "b2e73c2449294c631ea11590f6dcc8ec"
  sha1: "4c55482b2e5f98a0c4831de57edf1a7ab4b1662e"
  verified_sha1: "4c55482b2e5f98a0c4831de57edf1a7ab4b1662e"
}
