source_file: "IPHON8PLUShSLI0040NRD-IMG_0219.dng"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "7eef5a27"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "757b74a6c0c959b7c02ea8887d58237d"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "a491620542cb3ff8b99ccc1ab373e2eaf4f0f041"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "13109852"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931719"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/IPHON8PLUShSLI0040NRD-IMG_0219.dng"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".dng"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/tiff"
  want_quality: 10
}
exif: {
  want_camera_model: "Apple iPhone 8 Plus"
  want_photo_id: "2017-10-10 12:07:41.194 +0000 UTC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "TODO: implement decoding dng"
  skip: true
}
video_phash: {
  comment: "No Video Data"
}
