source_file: "IPHON8PLUShSLI0020NRD-IMG_0218.jpeg"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "89dc0055"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "b26ea2745794033bed9b7e0357a44770"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "0b37a5ece29a21a49dfab3d1956cae2b320bcd6d"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "3838886"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931701"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/IPHON8PLUShSLI0020NRD-IMG_0218.jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "44cd36094724d9fe"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "ff8181c3c38380db.9e9a946861c9cecc"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "KP44HB/fotFR2lKpSuVScFvLsjAw3F4RxbkgZGuqdnHDzsGAWXxwqqcWZy05xZHopsi4bMLEKWGVEunnppORyfAH9m6Y4orf"
  want_quality: 20
}
exif: {
  want_camera_model: "Apple iPhone 8 Plus"
  want_photo_id: "2017-10-10 12:07:28.518 +0000 UTC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "44cd36094724d9fe"
  want_nr90_hash: "ff8181c3c38380db.9e9a946861c9cecc"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "89dc0055"
  verified_crc32: "89dc0055"
  md5: "b26ea2745794033bed9b7e0357a44770"
  verified_md5: "b26ea2745794033bed9b7e0357a44770"
  sha1: "0b37a5ece29a21a49dfab3d1956cae2b320bcd6d"
  verified_sha1: "0b37a5ece29a21a49dfab3d1956cae2b320bcd6d"
}
