source_file: "IPHONE11hSLI0064NRD.dng"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "4da35eb9"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "e226791e8370c1f158351a371244f36b"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "2ba2194e32d084f4f95d553ed1e0048e990b82d5"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "Apple iPhone 11  D0BA9B66-D3D0-4C71-854D-3A46A36753FE"
  want_quality: 100
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "15206794"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931781"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/IPHONE11hSLI0064NRD.dng"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".dng"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/tiff"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "XMPDocumentID"
  want_hash: "CEE8F641053E12334BCAE205E585F5DB"
  want_quality: 100
}
exif: {
  want_camera_model: "Apple iPhone 11"
  want_photo_id: "D0BA9B66-D3D0-4C71-854D-3A46A36753FE"
  want_unique_photo_id: true
}
xmp: {
  want_document_id: "CEE8F641053E12334BCAE205E585F5DB"
}
img_phash: {
  comment: "TODO: implement decoding dng"
  skip: true
}
video_phash: {
  comment: "No Video Data"
}
