source_file: "Nikon D3000 2539678715.jpg"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "e026659d"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "6a855569f88c28d70778dd39aebca776"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "441b4a4b061397daf1350345325484e9c69efd8a"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "NIKON D3000 7400454 939 BASIC"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "950272"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931859"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/Nikon D3000 2539678715.jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "ec3143461c9a3ee5"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "fbffffbdb13e0c00.3c682bae985337b5"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "4HIYczRV5dG04EqeC4XEl1p4ira+sqfspa5P4OZXny+GPS88g6S2z14vD4dO/D48E5H9cmyVH5pabFn/cT70yHDNtCK98aql"
  want_quality: 20
}
exif: {
  want_camera_model: "NIKON D3000"
  want_camera_serial: "7400454"
  want_photo_id: "939 BASIC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "ec3143461c9a3ee5"
  want_nr90_hash: "fbffffbdb13e0c00.3c682bae985337b5"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "e026659d"
  verified_crc32: "e026659d"
  md5: "6a855569f88c28d70778dd39aebca776"
  verified_md5: "6a855569f88c28d70778dd39aebca776"
  sha1: "441b4a4b061397daf1350345325484e9c69efd8a"
  verified_sha1: "441b4a4b061397daf1350345325484e9c69efd8a"
}
