source_file: "NIKON D300 4085317 69139.NEF"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "f717ef3b"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "bc1001ce33faeca05fdc2e21cdafee47"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "e6f5546bd7ffc6330dcc5b8f2f620827d529883f"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "NIKON D300 4085317 69139 RAW"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "11427343"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931854"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/NIKON D300 4085317 69139.NEF"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".NEF"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/tiff"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "1c78610709f0fe3e"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "2038bcf8fc08.9b1bbf9e8f174787"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "JOYNw4VqR9eiJNFDQ2dVpGWStugO0mdGsr22JPC2klh9DpuWtulnPMXmRjAyJPpmK7HQ2g2ytsnvErSYjtCWtoHH54/C4HCy"
  want_quality: 20
}
exif: {
  want_camera_model: "NIKON D300"
  want_camera_serial: "4085317"
  want_photo_id: "69139 RAW"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "1c78610709f0fe3e"
  want_nr90_hash: "2038bcf8fc08.9b1bbf9e8f174787"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "f717ef3b"
  verified_crc32: "f717ef3b"
  md5: "bc1001ce33faeca05fdc2e21cdafee47"
  verified_md5: "bc1001ce33faeca05fdc2e21cdafee47"
  sha1: "e6f5546bd7ffc6330dcc5b8f2f620827d529883f"
  verified_sha1: "e6f5546bd7ffc6330dcc5b8f2f620827d529883f"
}
