source_file: "P1000hSLI0100NR2D.jpeg"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "32c8ee3c"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "6b3f413bf56b60ef1aa581e8f5fb9f23"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "e74623de0a48dc587320a88d71ed7cebd7cc82c6"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "NIKON COOLPIX P1000 30001701 2018-09-18 20:46:11 +0000 UTC FINE"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "7540217"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931935"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/P1000hSLI0100NR2D.jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "64fb68d47244d5e"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "bf03a1c3e78190db.929ab44861c8cacc"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "DXsYrFfi+R0r+lT6m8B4yGZ4u3J1Rj4MrcUUrJOA83GXQyEgWXw4eDkPOQ4Exw4NYtWwtG2kTw4eMlV1Ux7b25/jFkfWHH1O"
  want_quality: 20
}
exif: {
  want_camera_model: "NIKON COOLPIX P1000"
  want_camera_serial: "30001701"
  want_photo_id: "2018-09-18 20:46:11 +0000 UTC FINE"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "64fb68d47244d5e"
  want_nr90_hash: "bf03a1c3e78190db.929ab44861c8cacc"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "32c8ee3c"
  verified_crc32: "32c8ee3c"
  md5: "6b3f413bf56b60ef1aa581e8f5fb9f23"
  verified_md5: "6b3f413bf56b60ef1aa581e8f5fb9f23"
  sha1: "e74623de0a48dc587320a88d71ed7cebd7cc82c6"
  verified_sha1: "e74623de0a48dc587320a88d71ed7cebd7cc82c6"
}
