source_file: "PXL_20240818_015751859.jpg"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "f5e75a80"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "09c8c63fe04c87b9dd860d6359a99a41"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "cb5c68b3d556e2bbe94528cb4a285717514f671d"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1746798"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931998"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/PXL_20240818_015751859.jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "ce4cc3c34cccc3c3"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "803800f8ffffff.f8f88f4f0f7ffcf8"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "beVYPb46sEmQZeXZ80m2uW0uTe8Llk9NlSXJLd1IaIlikW0sbfsNZbfkk21UbaL8Ox2yM0iFLbLmNr2n2l10SbctOjtttSdm"
  want_quality: 20
}
exif: {
  want_camera_model: "Google Pixel 9 Pro"
  want_photo_id: "2024-08-17 19:57:51.859 +0000 UTC"
}
xmp: {}
img_phash: {
  want_azr_hash: "ce4cc3c34cccc3c3"
  want_nr90_hash: "803800f8ffffff.f8f88f4f0f7ffcf8"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "f5e75a80"
  verified_crc32: "f5e75a80\tBAD f5e75a80 != 20240818"
  md5: "09c8c63fe04c87b9dd860d6359a99a41"
  verified_md5: "09c8c63fe04c87b9dd860d6359a99a41"
  sha1: "cb5c68b3d556e2bbe94528cb4a285717514f671d"
  verified_sha1: "cb5c68b3d556e2bbe94528cb4a285717514f671d"
}
