source_file: "PXL_20240818_015751859.RAW-01.COVER.dng"
want_err: true
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "be9154ef"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "e496d864ebce5f3eb5b7e98be6feb727"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "3ffe4629a828e45ecc9c16ddb91bed5057f417b6"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "15382134"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737931993"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/PXL_20240818_015751859.RAW-01.COVER.dng"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".dng"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/tiff"
  want_quality: 10
}
exif: {
  want_camera_model: "Google Pixel 9 Pro"
  want_photo_id: "2024-08-17 19:57:51.89255 +0000 UTC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "TODO: implement decoding dng"
  skip: true
}
video_phash: {
  comment: "No Video Data"
}
