source_file: "sample_960x540.avi"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "56340627"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "7d1255bc1411981b7141fd03bf8523dc"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "819b814bfbda464b8244a8e00c53d0fc96dd9da0"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "608490"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1739785344"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/sample_960x540.avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "video/x-msvideo"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "VideoPHashRicop"
  want_hash: "dbeb74760b8b0403.2a55aa55aa55aa55"
  want_quality: 20
}
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "No image data"
}
video_phash: {
  want_ricop_hash: "dbeb74760b8b0403.2a55aa55aa55aa55"
}
checksum: {
  crc32: "56340627"
  verified_crc32: "56340627"
  md5: "7d1255bc1411981b7141fd03bf8523dc"
  verified_md5: "7d1255bc1411981b7141fd03bf8523dc"
  sha1: "819b814bfbda464b8244a8e00c53d0fc96dd9da0"
  verified_sha1: "819b814bfbda464b8244a8e00c53d0fc96dd9da0"
}
