source_file: "sample_2560x1440.avi"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "bd1dfe5c"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "9ae77f9793b0621224e4e5ef658a42ed"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "0883e2fa9a12f293db0c8247cd4dee4b7dd72e5e"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "16528270"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1739785212"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/sample_2560x1440.avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "video/x-msvideo"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "VideoPHashRicop"
  want_hash: "f801e7384147b7c9.2a55aa55aa55aa55"
  want_quality: 20
}
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "No image data"
}
video_phash: {
  want_ricop_hash: "f801e7384147b7c9.2a55aa55aa55aa55"
}
checksum: {
  crc32: "bd1dfe5c"
  verified_crc32: "bd1dfe5c"
  md5: "9ae77f9793b0621224e4e5ef658a42ed"
  verified_md5: "9ae77f9793b0621224e4e5ef658a42ed"
  sha1: "0883e2fa9a12f293db0c8247cd4dee4b7dd72e5e"
  verified_sha1: "0883e2fa9a12f293db0c8247cd4dee4b7dd72e5e"
}
