source_file: "sample_1920x1080.avi"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "3e3d34ef"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "49c64d5d240cf9ef41a517dbed58a5fd"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "fc4409a9b2943331b9dfd4b1b90d41aa90b1a2c3"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "9909100"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1739785156"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/sample_1920x1080.avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "video/x-msvideo"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "VideoPHashRicop"
  want_hash: "f801e7384147b7c9.2a55aa55aa55aa55"
  want_quality: 20
}
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "No image data"
}
video_phash: {
  want_ricop_hash: "f801e7384147b7c9.2a55aa55aa55aa55"
}
checksum: {
  crc32: "3e3d34ef"
  verified_crc32: "3e3d34ef"
  md5: "49c64d5d240cf9ef41a517dbed58a5fd"
  verified_md5: "49c64d5d240cf9ef41a517dbed58a5fd"
  sha1: "fc4409a9b2943331b9dfd4b1b90d41aa90b1a2c3"
  verified_sha1: "fc4409a9b2943331b9dfd4b1b90d41aa90b1a2c3"
}
