source_file: "sample_3840x2160.avi"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "2646acff"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "086f08e16c4b917133ac9609b62cab1c"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "e123bca29f3e84864ab3010aab792f99220dc3c9"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "35673024"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1739785340"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/sample_3840x2160.avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".avi"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "video/x-msvideo"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "VideoPHashRicop"
  want_hash: "f801e7384147b7c9.2a55aa55aa55aa55"
  want_quality: 20
}
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "No image data"
}
video_phash: {
  want_ricop_hash: "f801e7384147b7c9.2a55aa55aa55aa55"
}
checksum: {
  crc32: "2646acff"
  verified_crc32: "2646acff"
  md5: "086f08e16c4b917133ac9609b62cab1c"
  verified_md5: "086f08e16c4b917133ac9609b62cab1c"
  sha1: "e123bca29f3e84864ab3010aab792f99220dc3c9"
  verified_sha1: "e123bca29f3e84864ab3010aab792f99220dc3c9"
}
