source_file: "Sony Ericsson C905.JPG"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "1bb835e6"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "165590979254bfb988e63eb5733d9d5e"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "6d31dd7a9dafbf72187770b63bdfae8bc7c3bf52"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "1281553"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932316"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/Sony Ericsson C905.JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "dc98ad46724b158e"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "1f0f0f0717802b3f.4745a3a292d51555"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "dIZH6ZdS45PB44Z+hT9m4T/OWjYjTamQN2zbL0j+GgEfxySk4pHn7w8gxbAG4HA5RyFzq3U/PXAykM4E9ZmowfOYm4Hw6HnE"
  want_quality: 20
}
exif: {
  want_camera_model: "Sony Ericsson C905"
  want_photo_id: "2009-02-05 10:37:36 +0000 UTC"
}
xmp: {}
img_phash: {
  want_azr_hash: "dc98ad46724b158e"
  want_nr90_hash: "1f0f0f0717802b3f.4745a3a292d51555"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "1bb835e6"
  verified_crc32: "1bb835e6"
  md5: "165590979254bfb988e63eb5733d9d5e"
  verified_md5: "165590979254bfb988e63eb5733d9d5e"
  sha1: "6d31dd7a9dafbf72187770b63bdfae8bc7c3bf52"
  verified_sha1: "6d31dd7a9dafbf72187770b63bdfae8bc7c3bf52"
}
