source_file: "Sony A6100 4078921458.jpg"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "184f4179"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "26ba9964fad692b052d60cc1ca54aadc"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "fee4268097442948b94095af72ed97a68f2eab84"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "10961490"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932223"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/Sony A6100 4078921458.jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "74ab07f1f083067c"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "8f0f0f0fffccf1ff.c0c080c7d7463037"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "eQHBwkNyf0RSetkBcgrCNVi0Zc3xekQzlQccLfbEnWBXbM+zYXH4/G5g25nRLYviv4mY1sdFaMjn2LtLkKhGtVRq6qTRaH5/"
  want_quality: 20
}
exif: {
  want_camera_model: "SONY ILCE-6100"
  want_photo_id: "2019-11-04 16:02:21 +0000 UTC"
}
xmp: {}
img_phash: {
  want_azr_hash: "74ab07f1f083067c"
  want_nr90_hash: "8f0f0f0fffccf1ff.c0c080c7d7463037"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "184f4179"
  verified_crc32: "184f4179"
  md5: "26ba9964fad692b052d60cc1ca54aadc"
  verified_md5: "26ba9964fad692b052d60cc1ca54aadc"
  sha1: "fee4268097442948b94095af72ed97a68f2eab84"
  verified_sha1: "fee4268097442948b94095af72ed97a68f2eab84"
}
