source_file: "Sony A77 2416501744.jpg"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "8c2f2f90"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "6a76296b0bb83a9157bb9fabd092d221"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "b6dc2f15ccb35c1e24d7a0d5f2532fad3dc36fbe"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "8161460"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932258"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/Sony A77 2416501744.jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".jpg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "fd38a1ca383ea605"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "ff52161e141e0606.4d4d4bcb8a83a32b"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "TSUcdUcXUrmWarUL5rcwch58N6EkmHcO8e0c7NzTJZH+j4JKIcd/TC4WCcJtKr/4BUE5cMnblbhYegjc4p7ncI74fHjp+cMb"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "XMPDocumentID"
  want_hash: "DEF92186DF272963C04750273469F46C"
  want_quality: 100
}
exif: {
  want_camera_model: "SONY ILCA-77M2"
  want_photo_id: "2015-01-28 20:24:27 +0000 UTC"
}
xmp: {
  want_document_id: "DEF92186DF272963C04750273469F46C"
}
img_phash: {
  want_azr_hash: "fd38a1ca383ea605"
  want_nr90_hash: "ff52161e141e0606.4d4d4bcb8a83a32b"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "8c2f2f90"
  verified_crc32: "8c2f2f90"
  md5: "6a76296b0bb83a9157bb9fabd092d221"
  verified_md5: "6a76296b0bb83a9157bb9fabd092d221"
  sha1: "b6dc2f15ccb35c1e24d7a0d5f2532fad3dc36fbe"
  verified_sha1: "b6dc2f15ccb35c1e24d7a0d5f2532fad3dc36fbe"
}
