source_file: "sony_a7s_iii_07.arw"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "7cf18601"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "13c18ca746cef70c15ce0707f7f76417"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "df5c724e973b2b0c7a273de0ffb8d1468527cb37"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "13834240"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932840"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/sony_a7s_iii_07.arw"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".arw"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/tiff"
  want_quality: 10
}
exif: {
  want_camera_model: "SONY MODEL-NAME"
  want_photo_id: "2022-09-09 21:29:51.627 +0000 UTC"
}
xmp: {}
img_phash: {
  comment: "TODO: no thumbnail?"
  skip: true
}
video_phash: {
  comment: "No Video Data"
}
