source_file: "YDSC00059.JPG"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "e2369052"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "5363c2e0a3ed0d3a58319ed5f2557637"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "60f7882686aa030565c89269c8e14bab4fd4c8fc"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "SONY SLT-A77V 0909622764 885"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "19445201"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932549"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/YDSC00059.JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "59ad6ece2c1b1521"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "f8e08199f30301f7.1ef7d4ce98407872"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "O+KqSbaEkbx3utKCeaFp4mt7m1Gm2yaSVMfxUtWIqr0mqi9SUnoKP4nJMWaT8RVq6qqVIS41JXGSTZQiHlzi3ydBtkl6xdTO"
  want_quality: 20
}
exif: {
  want_camera_model: "SONY SLT-A77V"
  want_camera_serial: "0909622764"
  want_photo_id: "885"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "59ad6ece2c1b1521"
  want_nr90_hash: "f8e08199f30301f7.1ef7d4ce98407872"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "e2369052"
  verified_crc32: "e2369052"
  md5: "5363c2e0a3ed0d3a58319ed5f2557637"
  verified_md5: "5363c2e0a3ed0d3a58319ed5f2557637"
  sha1: "60f7882686aa030565c89269c8e14bab4fd4c8fc"
  verified_sha1: "60f7882686aa030565c89269c8e14bab4fd4c8fc"
}
