source_file: "YDSC01923-MFNR_HIGH.JPG"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "d32ad391"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "452cbe07fa486f970cd38021d7507efb"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "b8ca5a2b2807365b272fa0a93f1a8824b6e94061"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "SONY ILCA-77M2 173014736 24260"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "15137476"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932603"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/YDSC01923-MFNR_HIGH.JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "116743e1c3e347e1"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "7fcfcfdf20218101.14e26763a730b0f8"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "6DNJC3kidyfVafFOc2fZvspsW5hNSWhtjyNRcNO0NwWLjMMFy1PGiRMfPbrbHIPhwYfWIsLOYusn5LVppRqWjloBrIOTd10a"
  want_quality: 20
}
exif: {
  want_camera_model: "SONY ILCA-77M2"
  want_camera_serial: "173014736"
  want_photo_id: "24260"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "116743e1c3e347e1"
  want_nr90_hash: "7fcfcfdf20218101.14e26763a730b0f8"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "d32ad391"
  verified_crc32: "d32ad391"
  md5: "452cbe07fa486f970cd38021d7507efb"
  verified_md5: "452cbe07fa486f970cd38021d7507efb"
  sha1: "b8ca5a2b2807365b272fa0a93f1a8824b6e94061"
  verified_sha1: "b8ca5a2b2807365b272fa0a93f1a8824b6e94061"
}
