source_file: "YDSC01924-MFNR_LOW.JPG"
want_fingerprint: {
  want_kind: "CRC32"
  want_hash: "2a1b1c88"
  want_quality: 50
}
want_fingerprint: {
  want_kind: "MD5"
  want_hash: "bd47a38505981d81a4df3d8d9339698a"
  want_quality: 80
}
want_fingerprint: {
  want_kind: "SHA1"
  want_hash: "1cdc2fa4bc18cdd18a8ce2ab6c54b0710d38bc07"
  want_quality: 99
}
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "SONY ILCA-77M2 173014736 24265"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "filesize"
  want_hash: "17459165"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filedate"
  want_hash: "1737932667"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "filename"
  want_hash: "large_testdata/YDSC01924-MFNR_LOW.JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "fileextension"
  want_hash: ".JPG"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "mimetype"
  want_hash: "image/jpeg"
  want_quality: 10
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "c1e643e1c363c7e0"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "ffeeefff28212100.15e36761a530b8f8"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "4LueWyWRtrcBeSTtM0bctNOMpgTucz7KOuXjiiH9QWQ444TFjpYppZKYPQpZGoXKpjW8nqzbYpuHg5eXgaozSL4PRIZKZuLq"
  want_quality: 20
}
exif: {
  want_camera_model: "SONY ILCA-77M2"
  want_camera_serial: "173014736"
  want_photo_id: "24265"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "c1e643e1c363c7e0"
  want_nr90_hash: "ffeeefff28212100.15e36761a530b8f8"
}
video_phash: {
  comment: "No Video Data"
}
checksum: {
  crc32: "2a1b1c88"
  verified_crc32: "2a1b1c88"
  md5: "bd47a38505981d81a4df3d8d9339698a"
  verified_md5: "bd47a38505981d81a4df3d8d9339698a"
  sha1: "1cdc2fa4bc18cdd18a8ce2ab6c54b0710d38bc07"
  verified_sha1: "1cdc2fa4bc18cdd18a8ce2ab6c54b0710d38bc07"
}
